### ISSUE TITLE
Crash on iPad

### ISSUE THREAD

**Issue by xinatanil** [dvkch/SYEmailHelper#1]
We encountered an issue where the app crashes on the iPad because of a missing popoverPresentationController :( .

**Comment by dvkch** [comment]
Hi there! 

I just rewrote it all in Swift 4.2, and added proper popover support. Some class names have changed but the usage is very similar to the old Obj-C code, head over to the README to see an example.

Popover support is done by passing an additional `sender` parameter when showing the action sheet. If the sender is a `UIBarButtonItem` it will be associated to `popoverController.barButtonItem`, if it is a `UIView` subclass it will be used for `popoverController.sourceRect`.

This should fix your issue. Feel free to reopen if it doesn't, or open a new ticket if the rewrite added new issues for you :)

Syan
